### PR TITLE
WIP - DON'T MERGE - Reinstate shading for akka dns

### PR DESCRIPTION
**Pull request by fsat**
Issues
* [x] The `reference.conf` inside Akka DNS won't be shaded, we need to text replace `ru.` package ourselves.
* [ ] Akka DNS is not excluded from Ivy deps.
* [ ] Compile failure in `ServiceLocator` project. Something is still referencing `ru` package from the `root` package.

### CODE REVIEW

**Comment by fsat** [comment]
*Progress report*

Created shaded jar containing only Akka DNS.

```
Felixs-MBP-2:reactive-lib felixsatyaputra$ sbt clean shaded-akka-dns/assembly
[info] Loading global plugins from /Users/felixsatyaputra/.sbt/1.0/plugins
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /Users/felixsatyaputra/workspace/typesafe-fsat/reactive-lib/project
[info] Loading settings from build.sbt,version.sbt ...
[info] Set current project to reactive-lib (in build file:/Users/felixsatyaputra/workspace/typesafe-fsat/reactive-lib/)
[success] Total time: 0 s, completed 15/12/2017 4:54:11 PM
[info] Including from cache: akka-dns_2.11-2.4.2.jar
[info] Checking every *.class/*.jar file's SHA-1.
[info] Merging files...
[info] Packaging /Users/felixsatyaputra/workspace/typesafe-fsat/reactive-lib/shaded-akka-dns/target/2.11/shaded-akka-dns-2.11-0.3.5-SNAPSHOT.jar ...
[info] Done packaging.
[success] Total time: 0 s, completed 15/12/2017 4:54:12 PM

Felixs-MBP-2:reactive-lib felixsatyaputra$ jar tvf /Users/felixsatyaputra/workspace/typesafe-fsat/reactive-lib/shaded-akka-dns/target/2.11/shaded-akka-dns-2.11-0.3.5-SNAPSHOT.jar
   304 Fri Dec 15 16:54:12 AEDT 2017 META-INF/MANIFEST.MF
     0 Fri Dec 15 16:54:12 AEDT 2017 com/
     0 Fri Dec 15 16:54:12 AEDT 2017 com/lightbend/
     0 Fri Dec 15 16:54:12 AEDT 2017 com/lightbend/rp/
     0 Fri Dec 15 16:54:12 AEDT 2017 com/lightbend/rp/internal/
     0 Fri Dec 15 16:54:12 AEDT 2017 com/lightbend/rp/internal/akka/
     0 Fri Dec 15 16:54:12 AEDT 2017 com/lightbend/rp/internal/akka/io/
     0 Fri Dec 15 16:54:12 AEDT 2017 com/lightbend/rp/internal/ru/
     0 Fri Dec 15 16:54:12 AEDT 2017 com/lightbend/rp/internal/ru/smslv/
     0 Fri Dec 15 16:54:12 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/
     0 Fri Dec 15 16:54:12 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/
     0 Fri Dec 15 16:54:12 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/
  1479 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$$anonfun$11$$anonfun$apply$1.class
  2455 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$$anonfun$11.class
  1895 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$$anonfun$12.class
  1439 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$$anonfun$16$$anonfun$apply$2.class
  1480 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$$anonfun$16$$anonfun$apply$3.class
  2013 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$$anonfun$16.class
  1119 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$$anonfun$parseNameserverAddress$1.class
  1510 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$$anonfun$parseNameserverAddress$2.class
  1271 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$$anonfun$receive$1$$anonfun$1.class
  2661 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$$anonfun$receive$1$$anonfun$10.class
  1587 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$$anonfun$receive$1$$anonfun$13.class
  1822 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$$anonfun$receive$1$$anonfun$14.class
  1823 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$$anonfun$receive$1$$anonfun$15.class
  1507 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$$anonfun$receive$1$$anonfun$2.class
  1271 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$$anonfun$receive$1$$anonfun$3.class
  1507 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$$anonfun$receive$1$$anonfun$4.class
  1271 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$$anonfun$receive$1$$anonfun$5.class
  1508 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$$anonfun$receive$1$$anonfun$6.class
  2831 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$$anonfun$receive$1$$anonfun$7.class
  2841 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$$anonfun$receive$1$$anonfun$8.class
  2844 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$$anonfun$receive$1$$anonfun$9.class
  1996 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$$anonfun$receive$1$$anonfun$applyOrElse$1.class
  1996 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$$anonfun$receive$1$$anonfun$applyOrElse$2.class
  1844 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$$anonfun$receive$1$$anonfun$applyOrElse$3.class
  1844 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$$anonfun$receive$1$$anonfun$applyOrElse$4.class
  1845 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$$anonfun$receive$1$$anonfun$applyOrElse$5.class
  1845 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$$anonfun$receive$1$$anonfun$applyOrElse$6.class
  1845 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$$anonfun$receive$1$$anonfun$applyOrElse$7.class
 16537 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$$anonfun$receive$1.class
  5761 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$.class
  4305 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$CurrentRequest$.class
  6483 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$CurrentRequest.class
  2735 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$SrvResolved$.class
  3639 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver$SrvResolved.class
 15980 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/akka/io/AsyncDnsResolver.class
  1456 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/AsyncDnsProvider.class
  2620 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/AAAARecord$.class
  6829 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/AAAARecord.class
  2595 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/ARecord$.class
  6790 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/ARecord.class
  2560 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/Answer$.class
  5987 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/Answer.class
  2390 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/CNAMERecord$.class
  6922 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/CNAMERecord.class
  8460 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/DnsClient$$anonfun$ready$1.class
  3197 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/DnsClient$$anonfun$receive$1.class
  9383 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/DnsClient.class
  1251 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/DomainName$$anonfun$parse$1.class
  1590 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/DomainName$$anonfun$write$1$$anonfun$apply$1.class
  1918 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/DomainName$$anonfun$write$1.class
  3197 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/DomainName$.class
  1182 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/DomainName.class
  1740 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/Message$$anonfun$1.class
  1770 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/Message$$anonfun$2.class
  1770 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/Message$$anonfun$3.class
  1770 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/Message$$anonfun$4.class
  1622 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/Message$$anonfun$write$1.class
  1646 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/Message$$anonfun$write$2.class
  1646 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/Message$$anonfun$write$3.class
  1646 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/Message$$anonfun$write$4.class
  6135 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/Message$.class
 11217 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/Message.class
  7010 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/MessageFlags$.class
  7957 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/MessageFlags.class
   956 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/OpCode$.class
  1435 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/OpCode.class
  2821 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/Question$.class
  6487 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/Question.class
  2207 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/Question4$.class
  5159 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/Question4.class
  2207 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/Question6$.class
  5159 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/Question6.class
  1968 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/RecordClass$.class
  1994 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/RecordClass.class
  3743 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/RecordType$.class
  3413 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/RecordType.class
  3321 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/ResourceRecord$.class
  2867 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/ResourceRecord.class
  1316 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/ResponseCode$.class
  1838 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/ResponseCode.class
  2944 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/SRVRecord$.class
  8029 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/SRVRecord.class
  2225 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/SrvQuestion$.class
  5183 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/SrvQuestion.class
  2452 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/UnknownRecord$.class
  7225 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/UnknownRecord.class
   682 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/package$.class
   762 Fri Dec 15 16:33:44 AEDT 2017 com/lightbend/rp/internal/ru/smslv/akka/dns/raw/package.class
  1152 Fri Dec 15 16:54:12 AEDT 2017 reference.conf
```

**Comment by fsat** [comment]
Added the shaded Akka DNS as unmanaged jar of the `ServiceLocator` project.

Somehow we have the following failure:

```
[info] Compiling 3 Scala sources and 2 Java sources to /Users/felixsatyaputra/workspace/typesafe-fsat/reactive-lib/service-discovery/target/scala-2.11/classes ...
[error] /Users/felixsatyaputra/workspace/typesafe-fsat/reactive-lib/service-discovery/src/main/scala/com/lightbend/rp/servicediscovery/scaladsl/ServiceLocator.scala:20:42: object AsyncDnsResolver is not a member of package com.lightbend.rp.internal.akka.io
[error] Note: class AsyncDnsResolver exists, but it has no companion object.
[error] import com.lightbend.rp.internal.akka.io.AsyncDnsResolver.SrvResolved
[error]                                          ^
[error] /Users/felixsatyaputra/workspace/typesafe-fsat/reactive-lib/service-discovery/src/main/scala/com/lightbend/rp/servicediscovery/scaladsl/ServiceLocator.scala:29:8: Symbol 'term <root>.ru' is missing from the classpath.
[error] This symbol is required by ' <none>'.
[error] Make sure that term ru is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'package.class' was compiled against an incompatible version of <root>.
[error] import com.lightbend.rp.internal.ru.smslv.akka.dns.raw.SRVRecord
[error]        ^
[error] /Users/felixsatyaputra/workspace/typesafe-fsat/reactive-lib/service-discovery/src/main/scala/com/lightbend/rp/servicediscovery/scaladsl/ServiceLocator.scala:121:62: Symbol 'term <root>.ru' is missing from the classpath.
[error] This symbol is required by ' <none>'.
[error] Make sure that term ru is in your classpath and check for conflicting dependencies with `-Ylog-classpath`.
[error] A full rebuild may help if 'SRVRecord.class' was compiled against an incompatible version of <root>.
[error]   def translateResolved(protocol: Option[String], srvRecord: SRVRecord, addressARecord: Dns.Resolved): Seq[Service] =
[error]                                                              ^
[error] /Users/felixsatyaputra/workspace/typesafe-fsat/reactive-lib/service-discovery/src/main/scala/com/lightbend/rp/servicediscovery/scaladsl/ServiceLocator.scala:221:24: not found: value SrvResolved
[error]                   case SrvResolved(srvName, srvRecords) =>
[error]                        ^
[error] four errors found
[error] (reactive-lib-service-discovery/compile:compileIncremental) Compilation failed
[error] Total time: 6 s, completed 15/12/2017 9:27:30 PM
```

I've confirmed that `com/lightbend/rp/internal/akka/io/AsyncDnsResolver$.class` exists in the shaded jar, so companion object should be present?

Also not sure where the reference to the `ru` package from the `root` package may be coming from?

**Comment by fsat** [comment]
The `reference.conf` is now using shaded classes. Note `akka.io.dns.async-dns.provider-object` configuration:

```
192-168-1-5:reactive-lib felixsatyaputra$ sbt clean shaded-akka-dns/publishLocal
[info] Loading settings from plugins.sbt ...
[info] Loading global plugins from /Users/felixsatyaputra/.sbt/1.0/plugins
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /Users/felixsatyaputra/workspace/typesafe-fsat/reactive-lib/project
[info] Loading settings from build.sbt,version.sbt ...
[info] Set current project to reactive-lib (in build file:/Users/felixsatyaputra/workspace/typesafe-fsat/reactive-lib/)
[success] Total time: 0 s, completed 18/12/2017 11:05:09 AM
[info] Wrote /Users/felixsatyaputra/workspace/typesafe-fsat/reactive-lib/shaded-akka-dns/target/scala-2.11/shaded-akka-dns_2.11-0.3.5-SNAPSHOT.pom
[info] Including from cache: akka-dns_2.11-2.4.2.jar
[info] Checking every *.class/*.jar file's SHA-1.
[info] Merging files...
[info] Assembly up to date: /Users/felixsatyaputra/workspace/typesafe-fsat/reactive-lib/shaded-akka-dns/target/2.11/shaded-akka-dns-2.11-0.3.5-SNAPSHOT.jar
[info] :: delivering :: com.lightbend.rp#shaded-akka-dns_2.11;0.3.5-SNAPSHOT :: 0.3.5-SNAPSHOT :: integration :: Mon Dec 18 11:05:09 AEDT 2017
[info] 	delivering ivy file to /Users/felixsatyaputra/workspace/typesafe-fsat/reactive-lib/shaded-akka-dns/target/scala-2.11/ivy-0.3.5-SNAPSHOT.xml
[info] 	published shaded-akka-dns_2.11 to /Users/felixsatyaputra/.ivy2/local/com.lightbend.rp/shaded-akka-dns_2.11/0.3.5-SNAPSHOT/jars/shaded-akka-dns_2.11-assembly.jar
[info] 	published shaded-akka-dns_2.11 to /Users/felixsatyaputra/.ivy2/local/com.lightbend.rp/shaded-akka-dns_2.11/0.3.5-SNAPSHOT/poms/shaded-akka-dns_2.11.pom
[info] 	published shaded-akka-dns_2.11 to /Users/felixsatyaputra/.ivy2/local/com.lightbend.rp/shaded-akka-dns_2.11/0.3.5-SNAPSHOT/jars/shaded-akka-dns_2.11.jar
[info] 	published shaded-akka-dns_2.11 to /Users/felixsatyaputra/.ivy2/local/com.lightbend.rp/shaded-akka-dns_2.11/0.3.5-SNAPSHOT/srcs/shaded-akka-dns_2.11-sources.jar
[info] 	published shaded-akka-dns_2.11 to /Users/felixsatyaputra/.ivy2/local/com.lightbend.rp/shaded-akka-dns_2.11/0.3.5-SNAPSHOT/docs/shaded-akka-dns_2.11-javadoc.jar
[info] 	published ivy to /Users/felixsatyaputra/.ivy2/local/com.lightbend.rp/shaded-akka-dns_2.11/0.3.5-SNAPSHOT/ivys/ivy.xml
[success] Total time: 0 s, completed 18/12/2017 11:05:09 AM

192-168-1-5:reactive-lib felixsatyaputra$ jar xvf /Users/felixsatyaputra/.ivy2/local/com.lightbend.rp/shaded-akka-dns_2.11/0.3.5-SNAPSHOT/jars/shaded-akka-dns_2.11.jar reference.conf
 inflated: reference.conf

192-168-1-5:reactive-lib felixsatyaputra$ cat reference.conf
akka {
  actor {
    deployment {
      /IO-DNS/async-dns {
        mailbox = "unbounded"
        router = "round-robin-pool"
        nr-of-instances = 1
      }
    }
  }
  io {
    dns {
      async-dns {
        provider-object = "com.lightbend.rp.internal.ru.smslv.akka.dns.AsyncDnsProvider"

        min-positive-ttl = 0s
        max-positive-ttl = 1d
        negative-ttl = 10s

        resolve-ipv4 = true
        resolve-ipv6 = true
        resolve-srv  = false

        # How often to sweep out expired cache entries.
        # Note that this interval has nothing to do with TTLs
        cache-cleanup-interval = 120s

        # The IPs of nameservers to use e.g.
        # akka.io.dns.async-dns {
        #   nameservers = ["8.8.8.8", "8.8.4.4"]
        # }
        nameservers = []

        # Whether to use the system's /etc/resolv.conf in place
        # of nameservers
        resolv-conf = off

        # The time that a request is allowed to live before being discarded
        # given no reply. The lower bound of this should always be the amount
        # of time to reasonably expect a DNS server to reply within.
        request-ttl = 5s
      }
    }
  }
}
```

**Comment by longshorej** [comment]
I'm thinking that at this point we may want to fork [Akka DNS](https://github.com/ilya-epifanov/akka-dns) and publish to Maven Central ourselves.

**Comment by patriknw** [comment]
Perhaps just copy the relevant code and embed inside our own lib?

**Comment by longshorej** [comment]
Hrm, yeah maybe that's the way to go. Certainly less effort. Thanks for the suggestion!

**Comment by fsat** [comment]
I think if we were to embed the code inside our own lib, we need to move the package `akka.io ->  com.lightbend.rp.internal.akka.io` ourselves.

If we don't do this, the embedded code will still sit on `akka.io` package, and I think this may prevent user to specify their own version of Akka DNS.

**Comment by longshorej** [comment]
Closing this - thanks for the discussion @fsat. See #47 for the approach taken for now.

**Comment by fsat** [comment]
Thanks @longshorej !

**Pull request closed without merging**
