### PR TITLE
Update Akka Management to 0.13.0

### LINKED ISSUE #57: Update to latest Akka Management
There have been a number of upstream improvements, including better logging when Kubernetes API calls fail.

https://github.com/akka/akka-management/issues/137

### PR DESCRIPTION
**Pull request by TimMoore**
Fixes #57 

Notable changes:

- The default akka-management port is now 8558, instead of 19999 (this is more consistent now than before, which was accidental that we had the 1999 value there in a few places)
- Management bind port and fallback port of contact points should default to the same
- Add a "Role-Based Access Control" heading
- additional logging info
- Documentation: Kuberentes API Akka remoting port
- Spell out Akka 2.5 requirement in docs
- AsyncEcsSimpleServiceDiscovery -- listTaskArns needs a cluster name
- ECS service discovery improvements

Full details about changes: https://github.com/akka/akka-management/milestone/12?closed=1

### CODE REVIEW

**Comment by TimMoore** [comment]
I haven't done extensive testing of this (just `sbt test`). Can try it in Online Auction/Chirper if needed.

**Comment by ktoso** [comment]
If it uses bootstrap then that would be good to test; to make sure the right management port is used / set up

**Comment by TimMoore** [comment]
Yeah, good point... I was kind of hoping I could hand off to someone else, but if nobody gets to it first, I can do it. I just wanted to warn whoever might merge this to test it first or maybe hold off until someone can.

**Comment by mitkus** [comment]
I've tested this change on minikube, cluster bootstrap seems to work fine. However, Lightbend Orchestration overrides akka-management port to 10001? That's what logs tell me:

```
[akka.tcp://ClusterSystem@172.17.0.10:10000/system/bootstrapCoordinator] Located service members with name: [actorSystemName=ClusterSystem]: [172.17.0.10:Some(10001), 172.17.0.8:Some(10001), 172.17.0.6:Some(10001), 172.17.0.9:Some(10001), 172.17.0.7:Some(10001)]
[INFO] [05/15/2018 12:11:28.866] [ClusterSystem-akka.actor.default-dispatcher-15] [akka.tcp://ClusterSystem@172.17.0.10:10000/system/bootstrapCoordinator] Ensuring probing actor: contactPointProbe-172.17.0.9-10001
[INFO] [05/15/2018 12:11:28.867] [ClusterSystem-akka.actor.default-dispatcher-15] [akka.tcp://ClusterSystem@172.17.0.10:10000/system/bootstrapCoordinator] Ensuring probing actor: contactPointProbe-172.17.0.10-10001
[INFO] [05/15/2018 12:11:28.867] [ClusterSystem-akka.actor.default-dispatcher-15] [akka.tcp://ClusterSystem@172.17.0.10:10000/system/bootstrapCoordinator] Ensuring probing actor: contactPointProbe-172.17.0.6-10001
[INFO] [05/15/2018 12:11:28.868] [ClusterSystem-akka.actor.default-dispatcher-15] [akka.tcp://ClusterSystem@172.17.0.10:10000/system/bootstrapCoordinator] Ensuring probing actor: contactPointProbe-172.17.0.7-10001
[INFO] [05/15/2018 12:11:28.868] [ClusterSystem-akka.actor.default-dispatcher-15] [akka.tcp://ClusterSystem@172.17.0.10:10000/system/bootstrapCoordinator] Ensuring probing actor: contactPointProbe-172.17.0.8-10001
[INFO] [05/15/2018 12:11:28.869] [ClusterSystem-akka.actor.default-dispatcher-15] [akka.tcp://ClusterSystem@172.17.0.10:10000/system/bootstrapCoordinator] Initiating new cluster, self-joining [akka.tcp://ClusterSystem@172.17.0.10:10000]. Other nodes are expected to locate this cluster via continued contact-point probing.
```

**Comment by TimMoore** [comment]
Thanks for checking @mitkus.

Took me a while to track down the port assignments.

It's happening here: https://github.com/lightbend/reactive-cli/blob/master/cli/shared/src/main/scala/com/lightbend/rp/reactivecli/runtime/kubernetes/AssignedPort.scala

It basically loops through all of the endpoints and counts up from 10000 (which also explains why Akka Remoting is listening on 10000).

It only does this for "undeclared" endpoints (i.e., port=0). It would probably be better to use well-known defaults when possible.

Anyway, I don't think it needs to block this change.

**Pull request merged**
