### PR TITLE
Upgrade to akka-management 0.15.0

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by ktoso** [comment]
Oh whoa, thanks!

**Comment by ktoso** [comment]
With Tim traveling and team meeting now I think we can assume he'll love this change anyway ;-)

**Comment by dwijnand** [comment]
1 reviewer's good enough for me! 😉

**Comment by TimMoore** [comment]
Yes, thanks!

**Comment by dwijnand** [comment]
Anyone know how to cut a release of reactive-lib?

**Pull request merged**
